name: Main Build
on:
  push:
    branches: ['main']

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # - uses: actions/checkout@v2
      #   with: 
      #     repository: crea-asia/crea-argocd
      #     token: ${{ secrets.API_TOKEN_GITHUB }}
      #     path: argocd
      
      # - uses: imranismail/setup-kustomize@v1
      # - run: |
      #     pushd argocd/sysapps-sources/overlays/dev/argocd
      #     kustomize edit set image $ECR_REGISTRY/$ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     popd

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.API_TOKEN_GITHUB }}
      #     author: ${{ github.actor }} <${{ github.actor }}@github.com>
      #     commit-message: Release  ${{ env.ECR_REPOSITORY }} image ${{ env.IMAGE_TAG }} 
      #     assignees: ${{ github.actor }}
      #     labels: |
      #       release
      #       automated pr
      #     reviewers: schmiman,Poomkrit,Becram
      #     title: Auto-Release ${{ env.ECR_REPOSITORY }} version ${{ env.IMAGE_TAG }}
      #     body: |
      #       Update report
      #       - PR created by ${{ github.actor }}
      #       - Image version ${{ env.IMAGE_TAG }}
      #       - Commits: ${{ github.event.head_commit.message }}
      #     branch: release-from-${{ env.ECR_REPOSITORY }}
      #     base: main
      #     path: argocd
      #     draft: false
      #     signoff: false
